name: Create and Commit Timeline XML

on:
  workflow_dispatch

jobs:
  build_xml:
    name: build and commit timeline xml
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install Saxon, Ant
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        wget https://sourceforge.net/projects/saxon/files/Saxon-HE/9.9/SaxonHE9-9-1-7J.zip/download && unzip download -d saxon && rm -rf download
    - name: Build
      run: |
        ant -f scripts/ant/build_timeline.xml
    - name: Commit files to repo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: created auden and musulin timeline xml
        branch: dev
        skip_dirty_check: true    
        skip_fetch: true
        file_pattern: ./data/meta/*.xml
